### ISSUE TITLE
Issue on startup the test server

### ISSUE THREAD

**Issue by cech12** [alcatrazEscapee/mcjunitlib#2]
Hey, 
I tried to setup your nice test lib in my environment. I followed the steps of the readme and add 2 tests for testing your lib.
Everytime I start the test server, I get this log:

```
[20:34:48] [main/UNITTEST] [co.al.mc.DedicatedTestServerLauncher/]: TestServerLauncher Starting
[20:34:48] [main/UNITTEST] [co.al.mc.DedicatedTestServerLauncher/]: Launching Launcher with arguments: --crashOnFailedTests, --gameDir, ., --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.forgeVersion, 36.0.4, --launchTarget, fmltestserver
[20:34:50] [main/UNITTEST] [co.al.mc.TestMain/]: TestMain launching
[20:34:59] [main/UNITTEST] [co.al.mc.TestMain/]: Removing previous test world...
[20:35:06] [main/UNITTEST] [co.al.mc.TestMain/]: Setting random seed: 6762956184618966637
[20:35:06] [Server thread/UNITTEST] [co.al.mc.DedicatedTestServer/]: Server Thread Starting
[20:35:13] [Server thread/UNITTEST] [UnitTests/]: Did not discover any tests to run.
[20:35:13] [Server thread/UNITTEST] [co.al.mc.DedicatedTestServer/]: Encountered an unexpected exception
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method net.minecraft.server.MinecraftServer.isAheadOfTime()Z from class com.alcatrazescapee.mcjunitlib.DedicatedTestServer
	at com.alcatrazescapee.mcjunitlib.DedicatedTestServer.func_240802_v_(DedicatedTestServer.java:148) ~[?:1.4.1-1.16.5] {re:classloading}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162] {}
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.server.MinecraftServer.isAheadOfTime()Z from class com.alcatrazescapee.mcjunitlib.DedicatedTestServer
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_162] {}
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_162] {}
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_162] {}
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_162] {}
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_162] {}
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_162] {}
	... 3 more
> 
Process finished with exit code 1
```

It looks like, that there is an issue in accessing the private method `MinecraftServer#isAheadOfTime`.

I updated my mod to the same Forge version as your lib uses (1.16.5-36.0.4) and I tried the lib versions 1.4.1 and 1.4.3.
What am I doing wrong?

Here is my test branch: https://github.com/cech12/CeramicBucket/tree/feature/automated-tests
and the related commit: https://github.com/cech12/CeramicBucket/commit/e3f16b34576e14357dc12c66e0f4eb9af15c6ff5

Thanks for your help! :)

**Comment by alcatrazEscapee** [comment]
What on earth...?

At first glance, you're missing a mod id replacement [here](https://github.com/cech12/CeramicBucket/blob/e3f16b34576e14357dc12c66e0f4eb9af15c6ff5/build.gradle#L82). I doubt that would be the cause of the above issue though.

But on second glance... I'm wondering if this is some sort of deobf issue?

- The srg method in the linked crash is `func_240802_v_` which K9 is mapping me to `runServer` (mojmap)
- `isAheadOfTime` is as far as I can tell.. an MCP name for `func_212379_aT`... which is a totally different method (and I *cannot* seem to find the mojmap name for this one which makes me very suspicious)

I can try and help you debug this but I'm rather limited atm. as my main development computer is currently out of commission due to it, well, dying on me.


**Edit**

As some actual actionable advice: remove [this line](https://github.com/cech12/CeramicBucket/blob/e3f16b34576e14357dc12c66e0f4eb9af15c6ff5/build.gradle#L75), regen your run configs (`genIDERuns`), and run `runTestServer` again, and attach the full log there - but including all debug output.

**Comment by alcatrazEscapee** [comment]
OH after much searching I think I've found the offending location. (This is just my musing though so no idea if/when this will be able to be fixed)

https://github.com/alcatrazEscapee/mcjunitlib/blob/5fc9852adeb82b11f0876632a6257563a99fd4de/src/main/java/com/alcatrazescapee/mcjunitlib/DedicatedTestServer.java#L150

`func_212379_aT` is `haveTime`, which I *shadow* below:

https://github.com/alcatrazEscapee/mcjunitlib/blob/5fc9852adeb82b11f0876632a6257563a99fd4de/src/main/java/com/alcatrazescapee/mcjunitlib/DedicatedTestServer.java#L287-L290

This would indicate to me there's a remapping issue going on: Somewhere through compilation + deobf, that name is getting mapped to `isAheadOfTime` rather than the local `hasTime`. This is probably (technically) a Forge/tooling bug. Although, I would think it would be solvable via just changing the method name so it's not hiding the superclass method and name is uniquely instead.

**Comment by cech12** [comment]
Thanks for your super fast response! :)

> At first glance, you're missing a mod id replacement [here](https://github.com/cech12/CeramicBucket/blob/e3f16b34576e14357dc12c66e0f4eb9af15c6ff5/build.gradle#L82). I doubt that would be the cause of the above issue though.

> As some actual actionable advice: remove [this line](https://github.com/cech12/CeramicBucket/blob/e3f16b34576e14357dc12c66e0f4eb9af15c6ff5/build.gradle#L75), regen your run configs (`genIDERuns`), and run `runTestServer` again, and attach the full log there - but including all debug output.

I changed the modid and removed the mentioned line. The same errors are shown.
Here is the full log and the crash report: 
[latest.log](https://github.com/alcatrazEscapee/mcjunitlib/files/6651145/latest.log)
[crash-2021-06-14_22.37.45-server.txt](https://github.com/alcatrazEscapee/mcjunitlib/files/6651146/crash-2021-06-14_22.37.45-server.txt)

> This would indicate to me there's a remapping issue going on: Somewhere through compilation + deobf, that name is getting mapped to isAheadOfTime rather than the local hasTime. This is probably (technically) a Forge/tooling bug. Although, I would think it would be solvable via just changing the method name so it's not hiding the superclass method and name is uniquely instead.

So, there is nothing I can do than wait for the next update? :)

**Comment by cech12** [comment]
I forked your repository and changed the name of the described `haveTime` method. but then other errors occur: 
[latest.log](https://github.com/alcatrazEscapee/mcjunitlib/files/6653271/latest.log)

After testing around with the mappings it seems to be an issue with the used mappings. 
In my mod I am using the snapshot mappings `mappings channel: 'snapshot', version: '20210309-1.16.5'`. Your library uses `mappings channel: 'official', version: '1.16.5'`. These two mappings are very different.

I made a test mod that uses the same mappings and everything works fine. After changing the mappings to the snapshot one  the errors occur.

Changing my mod to the other mappings is a time consuming task. Maybe there is another option? It would be great if the used mappings can be unrelated. :)

**Comment by alcatrazEscapee** [comment]
`fg.deobf` **should** mean be enough to handle that case, although admittedly, as I'm using official mappings across all my mods I have not tested that case explicitly.

However, everything you showed me in that `latest.log` is working! The invalid class loading warnings are unfortunate but they don't actually cause any errors - they're due to JUnit searching for test classes (I believe). JUnit tests have ran, integration tests have attempted to, and because there were verification errors, the server is now just running (you can connect to it with a client, and try running / fixing the tests yourself with the `/integrationTest` command if you'd like, that's why it stays running)

That said, you do have an issue: you haven't provided structure files for your tests to load:

```
[15Jun2021 07:39:25.369] [Server thread/INFO] [com.alcatrazescapee.mcjunitlib.DedicatedTestServer/]: ERROR : Test 'DispenserTests.testDispenserPlacesLava' failed verification: No template 'ceramicbucket:dispenser/dispenser_lava' found.
[15Jun2021 07:39:25.370] [Server thread/INFO] [com.alcatrazescapee.mcjunitlib.DedicatedTestServer/]: ERROR : Test 'DispenserTests.testDispenserPlacesWater' failed verification: No template 'ceramicbucket:dispenser/dispenser_water' found.
[15Jun2021 07:39:25.371] [Server thread/INFO] [com.alcatrazescapee.mcjunitlib.DedicatedTestServer/]: ERROR : One more more tests failed verification.
[15Jun2021 07:39:25.371] [Server thread/UNITTEST] [com.alcatrazescapee.mcjunitlib.DedicatedTestServer/]: Unable to verify all tests.
```

This is the first step, before being able to run the in-game (integration) tests, it checks to see if all tests can be matched to the required NBT structures. And in this case they can't - you have not put the structures in the location that it is looking for.

*However*, just by looking at your latest commit, I'm not quite sure why it's looking for `ceramicbucket:dispenser/dispenser_lava` as opposed to `ceramicbucket:fluids/dispenser_lava`...

**Comment by cech12** [comment]
Ah okay, I will test that at the weekend :)

Maybe I changed some directories and names. That could lead to the different locations ^^ 

Thanks for your help :)

**Comment by cech12** [comment]
You were right! The nbt files lied at a wrong position. I corrected this and everything works fine! :D Thanks for your help, I will open a PR for the change. Then you can decide to add it. ;)
