### ISSUE TITLE
Trying to get library to run with MC 1.18

### ISSUE THREAD

**Issue by mikepoullas** [alcatrazEscapee/mcjunitlib#9]
I'm trying to get the library to run using MC 1.18 Is it even possible? Also, which 'run' do I execute because doing a Run with runServerTest returns the following:

[19:12:20] [main/UNITTEST]: TestServerLauncher Starting
[19:12:20] [main/UNITTEST]: Forge is calling, they want their ArgumentList back. This is a bug!
[19:12:20] [main/UNITTEST]: Error: 
java.lang.ClassNotFoundException: net.minecraftforge.userdev.ArgumentList
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.alcatrazescapee.mcjunitlib.DedicatedTestServerLauncher.main(DedicatedTestServerLauncher.java:34) [mcjunitlib-1.4.4-1.16.5_mapped_official_1.18.1.jar:1.4.4-1.16.5]

using runClient starts MC no problem but nothing is displayed from mcJunitLib. Any help would be greatly appreciated.

**Comment by alcatrazEscapee** [comment]
No, under no circumstances would be running the mod, compiled for a completely different Minecraft version, which has almost *entirely different class names*, and a modular Forge launch system which completely blows up the way this library worked, would've been possible.

See #4, everything there still applies (excepting the fact that Forge's support for game tests is still a work in progress...)

**Comment by mikepoullas** [comment]
Very unfortunate. Can you recommend an alternative for unit testing that would work with 1.18?
